Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
March 07, 2023 - 07:38:53
Django version 2.2, using settings 'Api_project_tt.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
[07/Mar/2023 07:40:56] "GET / HTTP/1.1" 200 16348
[07/Mar/2023 07:41:08] "GET / HTTP/1.1" 200 16348
[07/Mar/2023 07:41:10] "GET /admin/ HTTP/1.1" 200 3042
Performing system checks...

System check identified no issues (0 silenced).
March 07, 2023 - 07:40:53
Django version 2.2, using settings 'Api_project_tt.settings'
Starting development server at http://127.0.0.1:8008/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
[07/Mar/2023 07:42:52] "GET /admin/ HTTP/1.1" 200 3042
[07/Mar/2023 07:43:10] "GET /admin/ HTTP/1.1" 200 3042
[07/Mar/2023 07:43:11] "GET /admin/ HTTP/1.1" 200 3042
[07/Mar/2023 07:43:12] "GET /admin/ HTTP/1.1" 200 3042
[07/Mar/2023 07:48:29] "GET /admin/ HTTP/1.1" 200 3042
[07/Mar/2023 07:48:43] "GET /admin/auth/user/ HTTP/1.1" 200 6611
[07/Mar/2023 07:48:43] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[07/Mar/2023 07:51:37] "GET /admin/auth/user/ HTTP/1.1" 200 6611
[07/Mar/2023 07:51:37] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
March 07, 2023 - 08:09:35
Django version 2.2, using settings 'Api_project_tt.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
[07/Mar/2023 08:10:22] "GET /admin/auth/user/ HTTP/1.1" 200 6611
[07/Mar/2023 08:10:22] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[07/Mar/2023 08:12:13] "GET /admin/auth/user/ HTTP/1.1" 200 6611
[07/Mar/2023 08:12:13] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[07/Mar/2023 08:12:16] "GET /admin/auth/user/1/change/ HTTP/1.1" 200 13936
[07/Mar/2023 08:12:16] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[07/Mar/2023 08:12:16] "GET /static/admin/js/calendar.js HTTP/1.1" 200 7777
[07/Mar/2023 08:12:16] "GET /static/admin/js/SelectBox.js HTTP/1.1" 200 5755
[07/Mar/2023 08:12:16] "GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 12322
[07/Mar/2023 08:12:16] "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 20274
[07/Mar/2023 08:12:16] "GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
[07/Mar/2023 08:12:16] "GET /static/admin/img/icon-unknown.svg HTTP/1.1" 200 655
[07/Mar/2023 08:12:16] "GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 200 655
[07/Mar/2023 08:12:16] "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
[07/Mar/2023 08:12:16] "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
[07/Mar/2023 08:13:22] "GET /admin/auth/user/ HTTP/1.1" 200 6611
[07/Mar/2023 08:13:22] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[07/Mar/2023 08:19:01] "GET /admin/auth/user/ HTTP/1.1" 200 6611
[07/Mar/2023 08:19:01] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[07/Mar/2023 08:19:02] "GET /admin/auth/user/ HTTP/1.1" 200 6611
[07/Mar/2023 08:19:02] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[07/Mar/2023 08:20:09] "GET /admin/auth/user/ HTTP/1.1" 200 6611
[07/Mar/2023 08:20:09] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[07/Mar/2023 08:23:48] "GET / HTTP/1.1" 200 16348
[07/Mar/2023 08:24:10] "GET / HTTP/1.1" 200 16348
/Users/qui/Documents/Project/Api_project_tt/Api_project_tt/settings.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 07, 2023 - 08:10:14
Django version 2.2, using settings 'Api_project_tt.settings'
Starting development server at http://127.0.0.1:8008/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 60, in execute
    super().execute(*args, **options)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 95, in handle
    self.run(**options)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 102, in run
    autoreload.run_with_reloader(self.inner_run, **options)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/utils/autoreload.py", line 579, in run_with_reloader
    start_django(reloader, main_func, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/utils/autoreload.py", line 555, in start_django
    ensure_echo_on()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/utils/autoreload.py", line 83, in ensure_echo_on
    if fd.isatty():
AttributeError: 'NoneType' object has no attribute 'isatty'
Watching for file changes with StatReloader
Not Found: /
[07/Mar/2023 09:54:45] "GET / HTTP/1.1" 404 2034
[07/Mar/2023 09:54:58] "GET /admin/ HTTP/1.1" 302 0
[07/Mar/2023 09:54:58] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1819
Not Found: /v_help
[07/Mar/2023 09:55:12] "GET /v_help HTTP/1.1" 404 2070
Not Found: /
[07/Mar/2023 09:55:44] "GET / HTTP/1.1" 404 2034
Not Found: /
[07/Mar/2023 09:55:51] "GET / HTTP/1.1" 404 2034
Not Found: /
[07/Mar/2023 09:55:52] "GET / HTTP/1.1" 404 2034
Not Found: /
[07/Mar/2023 09:55:52] "GET / HTTP/1.1" 404 2034
Not Found: /
[07/Mar/2023 09:55:52] "GET / HTTP/1.1" 404 2034
Not Found: /
[07/Mar/2023 09:55:52] "GET / HTTP/1.1" 404 2034
Not Found: /
[07/Mar/2023 09:55:52] "GET / HTTP/1.1" 404 2034
Not Found: /
[07/Mar/2023 09:55:53] "GET / HTTP/1.1" 404 2034
Not Found: /
[07/Mar/2023 09:55:53] "GET / HTTP/1.1" 404 2034
Not Found: /
[07/Mar/2023 09:55:53] "GET / HTTP/1.1" 404 2034
Not Found: /
[07/Mar/2023 09:55:53] "GET / HTTP/1.1" 404 2034
[07/Mar/2023 09:57:01] "GET /admin/ HTTP/1.1" 302 0
[07/Mar/2023 09:57:01] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1819
[07/Mar/2023 09:57:11] "GET /help HTTP/1.1" 301 0
[07/Mar/2023 09:57:11] "GET /help/ HTTP/1.1" 200 138
[07/Mar/2023 09:57:15] "GET /help/ HTTP/1.1" 200 138
Not Found: /
[07/Mar/2023 09:57:22] "GET / HTTP/1.1" 404 2034
Performing system checks...

System check identified no issues (0 silenced).
March 07, 2023 - 09:54:39
Django version 2.2, using settings 'Api_project_tt.settings'
Starting development server at http://127.0.0.1:8008/
Quit the server with CONTROL-C.
/Library/Frameworks/Python.framework/Versions/3.8/bin/python3: can't open file 'manage.y': [Errno 2] No such file or directory
Watching for file changes with StatReloader
Not Found: /
[08/Mar/2023 06:00:38] "GET / HTTP/1.1" 404 2143
[08/Mar/2023 06:00:46] "GET /sunshine/ HTTP/1.1" 200 264
[08/Mar/2023 06:00:57] "GET /sunshine/ HTTP/1.1" 200 264
[08/Mar/2023 06:00:57] "GET /sunshine/ HTTP/1.1" 200 264
[08/Mar/2023 06:00:57] "GET /sunshine/ HTTP/1.1" 200 264
[08/Mar/2023 06:00:58] "GET /sunshine/ HTTP/1.1" 200 264
[08/Mar/2023 06:00:58] "GET /sunshine/ HTTP/1.1" 200 264
[08/Mar/2023 06:00:58] "GET /sunshine/ HTTP/1.1" 200 264
[08/Mar/2023 06:00:58] "GET /sunshine/ HTTP/1.1" 200 264
/Users/qui/Documents/Project/Api_project_tt/Api_project_tt/urls.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 08, 2023 - 06:00:31
Django version 2.2, using settings 'Api_project_tt.settings'
Starting development server at http://127.0.0.1:8008/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 60, in execute
    super().execute(*args, **options)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 95, in handle
    self.run(**options)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 102, in run
    autoreload.run_with_reloader(self.inner_run, **options)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/utils/autoreload.py", line 579, in run_with_reloader
    start_django(reloader, main_func, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/utils/autoreload.py", line 555, in start_django
    ensure_echo_on()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/utils/autoreload.py", line 83, in ensure_echo_on
    if fd.isatty():
AttributeError: 'NoneType' object has no attribute 'isatty'
